name: trigger test in another repository
on: workflow_dispatch
jobs:
 read-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # List the directories and verify file exists
      - name: List directories
        run: |
          ls -R selenium/tree
          ls -R  /src/test/java/jsonfiles

      # Now try reading the JSON file
      - name: Read JSON file
        run: |
          cat src/test/java/jsonfiles/customer.json
