name: Run tests maven with trigger
'on':
  repository_dispatch:
    types:
      - my-event
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Chechout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn test
      - name: Clean previous Allure results and report
        run: rm -rf target/allure-results
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results -o allure-report --clean
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '${{ secrets.REPO_A }}'
          publish_dir: ./allure-report
          publish_branch: allure-report
          keep_files: false
          
  jobs: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: '${{ secrets.SMTP_USERNAME }}'
          password: '${{ secrets.SMTP_PASSWORD }}'
          subject: GitHub Actions Test Email
          body: |
            This is a test email sent from a GitHub Action!
            - Repository: ${{ github.repository }}
            - Commit SHA: ${{ github.sha }}
          to: tharakaindradasa93@gmail.com
          from: '${{ secrets.SMTP_USERNAME }}'
