name: trigger test in another repository
on: workflow_dispatch
jobs:
  trigger-test:
     runs-on: ubuntu-latest
     steps:
      - name: trigger the automated test in another repo
        uses: SachinTharaka/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACC }}
          repository: SachinTharaka/qa_privaterepo
          event-type: my-event
